### ISSUE TITLE
Add server_id

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/BCF-XML#233] opened 2020-11-23 09:21 UTC
Since Topic Index is deprecated (https://github.com/buildingSMART/BCF-API/issues/202), we should add support for server_id also in BCF-XML.

Acceptance criteria
_____
[ ] server_id is available in BCF-XML
[ ] Index deprecation documentation refers to the server_id property

**Comment by jasollien** [comment] 2020-11-23 13:28
Had a comment regarding this: https://github.com/buildingSMART/BCF-XML/issues/232#issuecomment-732063811

**Comment by ykulbak** [comment] 2020-11-24 04:36
Closing, duplicate of #232

**Closed by ykulbak** 2020-11-24 04:36 UTC
